spring:
  profiles:
    active: dev
mybatis-plus:
  type-aliases-package: com.education.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**/*.xml